#ifndef COMMUNICATION_H
#define COMMUNICATION_H

#define ID_CARTE 0x1

void SendTermine(void);//Envoie le message terminé
void SendAtteint(void);
void SendBloque(void);
void SendArretUrgenceTermine(void);//Terminé avec en plus l'info sur la distance ou l'angle parcourue
void SendPong(void);//Envoie le message Pong
void SendAck(char ack);//Envoie le message Reçu
void SendPosition();  //Envoi les coordonnées (X,Y,Théta) du robot
void SendMesure(char Type); //Envoi au PC les infos pour calibrer les PID
void SendVariable(float val);

void TraiterMessage(MESSAGE * MessageRecu);

int CPUReset(void);

#define	Carte_Fcy	0
#define	Carte_Tcy	1
#define	Carte_Te	2
#define	Carte_Fe	3
#define	Carte_Fpwm	4
#define	Carte_Tpwm	5
#define	Mecanique_EntreAxe	6
#define	Mecanique_DiametreRoueD	7
#define	Mecanique_DiametreRoueG	8
#define	Mecanique_PuissanceMoteurD	9
#define	Mecanique_PuissanceMoteurG	10
#define	Mecanique_PuissanceMaxD	11
#define	Mecanique_PuissanceMaxG	12
#define	Mecanique_PuissanceMaxLongitudinal	13
#define	Mecanique_PuissanceMaxAngulaire	14
#define	Mecanique_VitesseLongitudinaleMax	15
#define	Mecanique_VitesseAngulaireMax	16
#define	Mecanique_VitesseRoueDMax	17
#define	Mecanique_VitesseRoueGMax	18
#define	Mecanique_NombrePasD	19
#define	Mecanique_NombrePasG	20
#define	Etat_DistanceTotale	21
#define	Etat_DistanceRoueD	22
#define	Etat_DistanceRoueG	23
#define	Etat_AngleBrut	24
#define	Etat_AngleReel	25
#define	Etat_VitesseLongitudinale	26
#define	Etat_VitesseAngulaire	27
#define	Etat_VitesseRoueD	28
#define	Etat_VitesseRoueG	29
#define	Etat_X	30
#define	Etat_Y	31
#define	Etat_EnvoiAuto	32
#define	Longitudinal_Desire	33
#define	Longitudinal_Consigne	34
#define	Longitudinal_VitesseMax	35
#define	Longitudinal_VitesseDemande	36
#define	Longitudinal_VitesseConsigne	37
#define	Longitudinal_VitesseConsignePrecedente	38
#define	Longitudinal_Acceleration	39
#define	Longitudinal_Decceleration	216
#define	Longitudinal_Est_Active	40
#define	Angulaire_Desire	41
#define	Angulaire_Consigne	42
#define	Angulaire_VitesseMax	43
#define	Angulaire_VitesseDemande	44
#define	Angulaire_VitesseConsigne	45
#define	Angulaire_VitesseConsignePrecedente	46
#define	Angulaire_Acceleration	47
#define	Angulaire_Decceleration	217
#define	Angulaire_Est_Active	48
#define	RoueD_Desire	49
#define	RoueD_Consigne	50
#define	RoueD_VitesseMax	51
#define	RoueD_VitesseDemande	52
#define	RoueD_VitesseConsigne	53
#define	RoueD_VitesseConsignePrecedente	54
#define	RoueD_Acceleration	55
#define	RoueD_Decceleration	218
#define	RoueD_Est_Active	56
#define	RoueG_Desire	57
#define	RoueG_Consigne	58
#define	RoueG_VitesseMax	59
#define	RoueG_VitesseDemande	60
#define	RoueG_VitesseConsigne	61
#define	RoueG_VitesseConsignePrecedente	62
#define	RoueG_Acceleration	63
#define	RoueG_Decceleration	219
#define	RoueG_Est_Active	64
#define	PidPositionLongitudinale_Erreur	65
#define	PidPositionLongitudinale_ErreurPrecedente	66
#define	PidPositionLongitudinale_IntegraleErreur	67
#define	PidPositionLongitudinale_DeriveErreur	68
#define	PidPositionLongitudinale_CommandeProportionelle	69
#define	PidPositionLongitudinale_CommandeIntegrale	70
#define	PidPositionLongitudinale_CommandeDerive	71
#define	PidPositionLongitudinale_Kp	72
#define	PidPositionLongitudinale_Ki	73
#define	PidPositionLongitudinale_Kd	74
#define	PidPositionLongitudinale_KpArret	75
#define	PidPositionLongitudinale_KiArret	76
#define	PidPositionLongitudinale_KdArret	77
#define	PidPositionLongitudinale_KpRoule	78
#define	PidPositionLongitudinale_KiRoule	79
#define	PidPositionLongitudinale_KdRoule	80
#define	PidPositionLongitudinale_Commande	81
#define	PidPositionAngulaire_Erreur	82
#define	PidPositionAngulaire_ErreurPrecedente	83
#define	PidPositionAngulaire_IntegraleErreur	84
#define	PidPositionAngulaire_DeriveErreur	85
#define	PidPositionAngulaire_CommandeProportionelle	86
#define	PidPositionAngulaire_CommandeIntegrale	87
#define	PidPositionAngulaire_CommandeDerive	88
#define	PidPositionAngulaire_Kp	89
#define	PidPositionAngulaire_Ki	90
#define	PidPositionAngulaire_Kd	91
#define	PidPositionAngulaire_KpArret	92
#define	PidPositionAngulaire_KiArret	93
#define	PidPositionAngulaire_KdArret	94
#define	PidPositionAngulaire_KpRoule	95
#define	PidPositionAngulaire_KiRoule	96
#define	PidPositionAngulaire_KdRoule	97
#define	PidPositionAngulaire_Commande	98
#define	PidVitesseLongitudinale_Erreur	99
#define	PidVitesseLongitudinale_ErreurPrecedente	100
#define	PidVitesseLongitudinale_IntegraleErreur	101
#define	PidVitesseLongitudinale_DeriveErreur	102
#define	PidVitesseLongitudinale_CommandeProportionelle	103
#define	PidVitesseLongitudinale_CommandeIntegrale	104
#define	PidVitesseLongitudinale_CommandeDerive	105
#define	PidVitesseLongitudinale_Kp	106
#define	PidVitesseLongitudinale_Ki	107
#define	PidVitesseLongitudinale_Kd	108
#define	PidVitesseLongitudinale_KpArret	109
#define	PidVitesseLongitudinale_KiArret	110
#define	PidVitesseLongitudinale_KdArret	111
#define	PidVitesseLongitudinale_KpRoule	112
#define	PidVitesseLongitudinale_KiRoule	113
#define	PidVitesseLongitudinale_KdRoule	114
#define	PidVitesseLongitudinale_Commande	115
#define	PidVitesseAngulaire_Erreur	116
#define	PidVitesseAngulaire_ErreurPrecedente	117
#define	PidVitesseAngulaire_IntegraleErreur	118
#define	PidVitesseAngulaire_DeriveErreur	119
#define	PidVitesseAngulaire_CommandeProportionelle	120
#define	PidVitesseAngulaire_CommandeIntegrale	121
#define	PidVitesseAngulaire_CommandeDerive	122
#define	PidVitesseAngulaire_Kp	123
#define	PidVitesseAngulaire_Ki	124
#define	PidVitesseAngulaire_Kd	125
#define	PidVitesseAngulaire_KpArret	126
#define	PidVitesseAngulaire_KiArret	127
#define	PidVitesseAngulaire_KdArret	128
#define	PidVitesseAngulaire_KpRoule	129
#define	PidVitesseAngulaire_KiRoule	130
#define	PidVitesseAngulaire_KdRoule	131
#define	PidVitesseAngulaire_Commande	132
#define	PidPositionD_Erreur	133
#define	PidPositionD_ErreurPrecedente	134
#define	PidPositionD_IntegraleErreur	135
#define	PidPositionD_DeriveErreur	136
#define	PidPositionD_CommandeProportionelle	137
#define	PidPositionD_CommandeIntegrale	138
#define	PidPositionD_CommandeDerive	139
#define	PidPositionD_Kp	140
#define	PidPositionD_Ki	141
#define	PidPositionD_Kd	142
#define	PidPositionD_KpArret	143
#define	PidPositionD_KiArret	144
#define	PidPositionD_KdArret	145
#define	PidPositionD_KpRoule	146
#define	PidPositionD_KiRoule	147
#define	PidPositionD_KdRoule	148
#define	PidPositionD_Commande	149
#define	PidPositionG_Erreur	150
#define	PidPositionG_ErreurPrecedente	151
#define	PidPositionG_IntegraleErreur	152
#define	PidPositionG_DeriveErreur	153
#define	PidPositionG_CommandeProportionelle	154
#define	PidPositionG_CommandeIntegrale	155
#define	PidPositionG_CommandeDerive	156
#define	PidPositionG_Kp	157
#define	PidPositionG_Ki	158
#define	PidPositionG_Kd	159
#define	PidPositionG_KpArret	160
#define	PidPositionG_KiArret	161
#define	PidPositionG_KdArret	162
#define	PidPositionG_KpRoule	163
#define	PidPositionG_KiRoule	164
#define	PidPositionG_KdRoule	165
#define	PidPositionG_Commande	166
#define	PidVitesseD_Erreur	167
#define	PidVitesseD_ErreurPrecedente	168
#define	PidVitesseD_IntegraleErreur	169
#define	PidVitesseD_DeriveErreur	170
#define	PidVitesseD_CommandeProportionelle	171
#define	PidVitesseD_CommandeIntegrale	172
#define	PidVitesseD_CommandeDerive	173
#define	PidVitesseD_Kp	174
#define	PidVitesseD_Ki	175
#define	PidVitesseD_Kd	176
#define	PidVitesseD_KpArret	177
#define	PidVitesseD_KiArret	178
#define	PidVitesseD_KdArret	179
#define	PidVitesseD_KpRoule	180
#define	PidVitesseD_KiRoule	181
#define	PidVitesseD_KdRoule	182
#define	PidVitesseD_Commande	183
#define	PidVitesseG_Erreur	184
#define	PidVitesseG_ErreurPrecedente	185
#define	PidVitesseG_IntegraleErreur	186
#define	PidVitesseG_DeriveErreur	187
#define	PidVitesseG_CommandeProportionelle	188
#define	PidVitesseG_CommandeIntegrale	189
#define	PidVitesseG_CommandeDerive	190
#define	PidVitesseG_Kp	191
#define	PidVitesseG_Ki	192
#define	PidVitesseG_Kd	193
#define	PidVitesseG_KpArret	194
#define	PidVitesseG_KiArret	195
#define	PidVitesseG_KdArret	196
#define	PidVitesseG_KpRoule	197
#define	PidVitesseG_KiRoule	198
#define	PidVitesseG_KdRoule	199
#define	PidVitesseG_Commande	200
#define	MouvementActuel_DistanceDemande	201
#define	MouvementActuel_AngleDemande	202
#define	MouvementActuel_DistanceDroiteDemande	203
#define	MouvementActuel_DistanceGaucheDemande	204
#define	MouvementActuel_Xc	205
#define	MouvementActuel_Yc	206
#define	MouvementActuel_PrecisionLongitudinale	207
#define	MouvementActuel_PrecisionAngulaire	208
#define	MouvementActuel_Type	209
#define	MouvementActuel_EnAvant	210
#define	MouvementActuel_Etape	211
#define	MouvementActuel_Termine	212
#define	MouvementActuel_TermineEnvoye	213
#define	MouvementActuel_TempsBlocage	214
#define	MouvementActuel_ConfigAsserv	215

#endif
